language: python
python: 3.4
env:
  - TOX_ENV=standard
  - TOX_ENV=flake8
  - TOX_ENV=docs
addons:
  apt:
    packages:
      - tree
install:
  - pip install tox
script:
  - mkdir build/
  - tox -e $TOX_ENV
  - tree -a build/
