deployments:
  my_first_repo_set:
    target: ../build/ready-git-repos
    defaults:
      base_url: https://github.com
      root: states
      cache: common
    repos:
      gathergit:
        defaults:
          repo: bechtoldt/gathergit
          root: gathergit
        branches:
          test: master
      alternatives:
        defaults:
          repo: puppet-community/puppet-alternatives
        branches:
          dev: 0.1.0
      apache:
        name: httpd
        defaults:
          repo: puppetlabs/puppetlabs-apache # upstream repository
        branches:
          test: master
          dev: master # branch
          prod:
            ref: 0.8.0 # tag
#      xfoo:
#        defaults:
#          repo: arbe/amytest
#          url: file:///tmp/mytest
#        branches:
#          dev: master
#      test:
#        defaults:
#          repo: arbe/amytest
#          url: file:///tmp/mytest
#        branches:
#          prod:
#            ref: master
#            root: w00t/
#          qa: b
#          dev: dev
      skeleton:
        defaults:
          repo: bechtoldt/saltstack-skeleton-formula
        branches:
          prod: master
      elasticsearch:
        defaults:
          repo: bechtoldt/saltstack-elasticsearch-formula
        branches:
          prod: master
      iscdhcp:
        branches:
          prod:
            ref: master
            root: iscdhcp
            repo: bechtoldt/saltstack-iscdhcp-formula
      opennebula:
        defaults:
          repo: bechtoldt/saltstack-opennebula-formula
        branches:
          prod:
            ref: master
            root: opennebula
  contrib_files_repo_set:
    target: ../build/ready-git-repos-contrib
    defaults:
      base_url: https://github.com
      root: contrib
      cache: common
    repos:
      opennebula:
        url: git@github.com:bechtoldt/saltstack-opennebula-formula.git # SSH
        defaults:
          repo: bechtoldt/saltstack-opennebula-formula
        branches:
          prod:
            ref: master
  saltstack_standard_states_env:
    target: ../build/saltstack-states
    cache: common
    defaults:
      base_url: https://github.com
      root: states
    repos:
      amavis:
        defaults:
          repo: bechtoldt/saltstack-amavis-formula.git
        branches:
          prod:
            ref: master
      aptcacherng:
        defaults:
          repo: bechtoldt/saltstack-aptcacherng-formula.git
        branches:
          prod:
            ref: master
      bash:
        defaults:
          repo: bechtoldt/saltstack-bash-formula.git
        branches:
          prod:
            ref: master
      binddns:
        defaults:
          repo: bechtoldt/saltstack-binddns-formula.git
        branches:
          prod:
            ref: master
      clamav:
        defaults:
          repo: bechtoldt/saltstack-clamav-formula.git
        branches:
          prod:
            ref: master
      cron:
        defaults:
          repo: bechtoldt/saltstack-cron-formula.git
        branches:
          prod:
            ref: master
      crypto:
        defaults:
          repo: bechtoldt/saltstack-crypto-formula.git
        branches:
          prod:
            ref: master
      dnsmasq:
        defaults:
          repo: bechtoldt/saltstack-dnsmasq-formula.git
        branches:
          prod:
            ref: master
      dovecot:
        defaults:
          repo: bechtoldt/saltstack-dovecot-formula.git
        branches:
          prod:
            ref: master
      duply:
        defaults:
          repo: bechtoldt/saltstack-duply-formula.git
        branches:
          prod:
            ref: master
      ebtables:
        defaults:
          repo: bechtoldt/saltstack-ebtables-formula.git
        branches:
          prod:
            ref: master
      elasticsearch:
        defaults:
          repo: bechtoldt/saltstack-elasticsearch-formula.git
        branches:
          prod:
            ref: master
      ferm:
        defaults:
          repo: bechtoldt/saltstack-ferm-formula.git
        branches:
          prod:
            ref: master
      file:
        defaults:
          repo: bechtoldt/saltstack-file-formula.git
        branches:
          prod:
            ref: master
      foreman:
        defaults:
          repo: bechtoldt/saltstack-foreman-formula.git
        branches:
          prod:
            ref: master
      git:
        defaults:
          repo: bechtoldt/saltstack-git-formula.git
        branches:
          prod:
            ref: master
      gitlab:
        defaults:
          repo: bechtoldt/gitlab-formula.git
        branches:
          prod:
            ref: master
      grub:
        defaults:
          repo: bechtoldt/saltstack-grub-formula.git
        branches:
          prod:
            ref: master
      haproxy:
        defaults:
          repo: bechtoldt/saltstack-haproxy-formula.git
        branches:
          prod:
            ref: master
      httpd:
        defaults:
          repo: bechtoldt/saltstack-httpd-formula.git
        branches:
          prod:
            ref: master
      iscdhcp:
        defaults:
          repo: bechtoldt/saltstack-iscdhcp-formula.git
        branches:
          prod:
            ref: master
      java:
        defaults:
          repo: bechtoldt/saltstack-java-formula.git
        branches:
          prod:
            ref: master
      keepalived:
        defaults:
          repo: bechtoldt/saltstack-keepalived-formula.git
        branches:
          prod:
            ref: master
