reposets:
  my_first_repo_set:
    target: /tmp/ready-git-repos
    defaults:
      base_url: https://github.com
      root: states
    repos:
      alternatives:
        repo: puppet-community/puppet-alternatives
        deploy:
          prod: master
      apache:
        name: httpd
        repo: puppetlabs/puppetlabs-apache
        url: https://github.com/puppetlabs/puppetlabs-apache
        deploy:
          dev: master # branch
          prod: 0.8.0 # tag
      test:
        repo: arbe/mytest
        url: file:///tmp/mytest
        deploy:
          prod:
            remote_ref: master
            root: w00t/
          qa: b
          dev: c21
      skeleton:
        repo: bechtoldt/saltstack-skeleton-formula
        deploy:
          prod: master
      elasticsearch:
        repo: bechtoldt/saltstack-elasticsearch-formula
        deploy:
          prod: master
      iscdhcp:
        repo: bechtoldt/saltstack-iscdhcp-formula
        deploy:
          prod:
            remote_ref: master
            root: iscdhcp
      opennebula:
        repo: bechtoldt/saltstack-opennebula-formula
        deploy:
          prod:
            remote_ref: master
            root: opennebula
  contrib_files_repo_set:
    target: /tmp/ready-git-repos-contrib
    defaults:
      base_url: https://github.com
      root: contrib
    repos:
      opennebula:
        repo: bechtoldt/saltstack-opennebula-formula
        deploy:
          prod:
            remote_ref: master


